sequenceDiagram
    participant ui as Cypress UI
    participant stubs as Cypress Stubs
    participant mocksocket as Mock Websocket Server
    note left of stubs: initial page load
    ui --> stubs: session handshake ✓
    ui --> stubs: token auth
    note left of stubs: websocket upgrade
    ui -->> mocksocket: fetch mockdata with fixture id e.g. 'homepage modal' ✓
    mocksocket -->> ui: send modal required stub data ✓
    ui -->> ui: open modal in response to websocket data